POST http://localhost:3001/api/blogs
Content-type: application/json

# {
#   "author": "Edsger W. Dijkstra",
#   "title": "Canonical string reduction",
#   "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html"
# }
# {
#   "title": "React patterns",
#   "author": "Michael Chan",
#   "url": "reactpatterns.com"
# }
{
  "title": "Codifying your future",
  "author": "Francisco Zavala",
  "url": "pacoderzavala.com"
}