PUT http://localhost:3001/api/blogs/c81d1837-3f18-4ffc-ad38-e275f484994e
Content-type: application/json

# {
#   "author": "Edsger W. Dijkstra",
#   "title": "Canonical string reduction",
#   "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
#   "likes": 1
# }

  # "title": "Canonical string reductions",
{
  "author": "Edsger W. Dijkstra",
  "likes": 2
}