PUT http://localhost:3001/api/blogs/1a811556-8f85-4d81-b3f0-19eb88bc79cd
Content-type: application/json

# {
#   "author": "Edsger W. Dijkstra",
#   "title": "Canonical string reduction",
#   "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
#   "likes": 1
# }

  # "title": "Canonical string reductions",
{
  "likes": 1
}