PUT http://localhost:3001/api/blogs/5d99541c-7baf-4acc-9f94-1bef3731e21c
Content-type: application/json

# {
#   "author": "Edsger W. Dijkstra",
#   "title": "Canonical string reduction",
#   "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
#   "likes": 1
# }

  # "title": "Canonical string reductions",
{
  "likes": 2
}