version: '3.9'

services:
  
  # client:
  #   image: client:v2.10
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   environment:
  #     - REACT_APP_SERVER_URL=http://localhost:3001
  #   ports:
  #     - 3000:3000

  # server:
  #   image: server:v2.10
  #   container_name: server
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3001:3001
  #   environment:
  #     - PORT=3001
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     - postgres
  
  postgres:
    image: postgres:alpine
    container_name: postgres-
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  
  # wiki_url:
  #   image: wiki_url:v2.10
  #   container_name: wiki_url
  #   build:
  #     context: ./cronjob
  #     dockerfile: Dockerfile
  #   environment:
  #     - SERVER_URL=http://server:3001/api/todos


volumes:
    database:
        driver: local